package bank.entity;
// Generated Jan 12, 2022 8:33:14 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * BankAccount generated by hbm2java
 */
public class BankAccount  implements Serializable {


     private String accountNumber;
     private BigDecimal amount;

    public BankAccount() {
    }

	
    public BankAccount(String accountNumber) {
        this.accountNumber = accountNumber;
    }
    public BankAccount(String accountNumber, BigDecimal amount) {
       this.accountNumber = accountNumber;
       this.amount = amount;
    }
   
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Override
    public String toString() {
        return accountNumber + " :: " + amount;
    }




}


